# Generated by Django 2.1.2 on 2019-03-12 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GeniusCooks', '0002_auto_20190312_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient_model',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GeniusCooks.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='step_model',
            name='recipe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='GeniusCooks.Recipe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recipe',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='GeniusCooks.Profile'),
        ),
    ]
